version: '3.8'

services:
  web:
    build: .
    container_name: minichat_web
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data # SQLite veri tabanı sıfırlanmasın diye klasöre bağlıyoruz
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/ecommerce.db
      # Eğer projede Ollama linki varsa, bunu konteynerin anlayacağı adrese çeviriyoruz
      - OllamaUrl=http://ollama:11434 

volumes:
  ollama_data: